apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: python-flask-docker
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-ee-swickers-tenant/python-flask-docker/python-flask-docker@sha256:5da99bc00c3fa84cf499a2fb0bc3befaaf2b7bf433fac590b1d9a4fc2b80b2ae
        name: container-image
        resources: {}
status: {}
