apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-flask-docker
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-flask-docker
    app.kubernetes.io/part-of: python-flask-docker
  name: python-flask-docker
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: python-flask-docker
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: python-flask-docker
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-ee-swickers-tenant/python-flask-docker/python-flask-docker@sha256:5da99bc00c3fa84cf499a2fb0bc3befaaf2b7bf433fac590b1d9a4fc2b80b2ae
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
