apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-flask-docker
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-flask-docker
    app.kubernetes.io/part-of: python-flask-docker
  name: python-flask-docker
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: python-flask-docker
status:
  loadBalancer: {}
